# Generated by Django 4.0.6 on 2022-07-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_user_id_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
