# Generated by Django 4.0.6 on 2022-07-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_order_get_price_alter_order_image_recipies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
