# Generated by Django 4.0.4 on 2022-07-29 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_deliverer_remove_user_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliverer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.deliverer'),
        ),
    ]
